project/apps/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import *

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
    path("unavailable/", unavailable, name="unavailable"),
]

project/apps/producto/urls.py
from django.urls import path

from .views import *

app_name = "producto"

urlpatterns = [
    path("", index, name="index"),
    path("producto/list/", ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("producto/form/", ProductoCategoriaCreate.as_view(), name="productocategoria_form"),
    path("producto/update/<int:pk>/", ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    path("producto/delete/<int:pk>/", ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
    path("producto/detail/<int:pk>/", ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("producto/", include("producto.urls")),
]

project/apps/producto/models.py
from django.db import models
from django.utils import timezone


class ProductoCategoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "categoría de productos"
        verbose_name_plural = "categorías de productos"


class Producto(models.Model):
    categoria_id = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, null=True, blank=True)
    nombre = models.CharField(max_length=100)
    unidad_medida = models.CharField(max_length=100, verbose_name="unidad de medida")
    cantidad = models.FloatField()
    precio = models.FloatField()
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")
    fecha_actualizacion = models.DateField(default=timezone.now, editable=False, verbose_name="fecha de actualización")

    def __str__(self) -> str:
        return f"{self.nombre} ${self.precio:.2f}"

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

project/apps/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/apps/producto/forms.py
from django import forms

from .models import *


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = ProductoCategoria
        fields = "__all__"

project/apps/core/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from .forms import *


def index(request):
    return render(request, "core/index.html")


def about(request: HttpRequest) -> HttpResponse:
    return render(request, "core/about.html")


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("core:index")
    else:  # if request.method == "GET":
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

def unavailable(request: HttpRequest) -> HttpResponse:
    return render(request, "core/unavailable.html")

project/apps/producto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import *
from .models import *


def index(request):
    return render(request, "producto/index.html")

class ProductoCategoriaList(ListView):
    model = ProductoCategoria

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = ProductoCategoria.objects.filter(nombre__icontains=consulta)
        else:
            object_list = ProductoCategoria.objects.all()
        return object_list

class ProductoCategoriaCreate(LoginRequiredMixin, CreateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")

class ProductoCategoriaUpdate(LoginRequiredMixin, UpdateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")

class ProductoCategoriaDelete(LoginRequiredMixin, DeleteView):
    model = ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")

class ProductoCategoriaDetail(DetailView):
    model = ProductoCategoria

project/apps/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}
    | Nosotros
{% endblock title %}

{% block content_title %}
  Acerca de nosotros...
{% endblock content_title %}

{% block content %}
  <div class="d-flex justify-content-center align-items-center" style="height: 50vh;">
    <div class="text-center">
      <h1 class="display-4">Bienvenido a Fútbol Store!</h1>
      <p class="lead">Somos amantes del fútbol! Creamos esta aplicación con el objetivo de brindarles a los usuarios la posibilidad de comprar y vender camisetas desde y hacia cualquier parte del mundo.</p>

      <h5>Nuestro Equipo</h5>
      
      <ul class="list-group">
        <li class="list-group-item">Lucas - CEO</li>
      </ul>
    </div>
  </div>
{% endblock content %}

project/apps/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> 
            Final Project
            {% block title %}  {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        {% include 'core/navbar.html' %}

        <div class="container px-4 px-lg-5">
            <h1 class="text-info mt-4">
                
                {% block content_title %}
                {% endblock content_title %}

            </h1>
            
            {% block content %}
            {% endblock content %}
  
        </div>
        
        {% include 'core/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/apps/core/templates/core/footer.html
<footer class="py-2 bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5 "><p class="m-0 text-center text-white">Copyright &copy; Hecho en enero de 2024</p></div>
</footer>

project/apps/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
    | Inicio
{% endblock title %}


{% block content_title %}
    FÚTBOL STORE
{% endblock content_title %}


{% block content %}
    
    {% if user.is_staff %}
        <div class="d-flex justify-content-xl-start">
            <a href="{% url 'admin:index' %}" class="btn btn-info w-25">Administración</a></button>
        </div>
    {% endif %}

    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/imagenes/portada.webp' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-monospace">Bienvenidos!</h1>
            <p>Aquí encontrarás camisetas de fútbol de todas partes del mundo.</p>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">Fútbol Store cuenta con un amplio stock de camisetas de fútbol. Vas a encontrar productos 100% originales y de máxima calidad.</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        {% include 'core/tarjeta.html' with titulo="Clubes Nacionales" imagen_url="https://pbs.twimg.com/media/EUOnwDEXsAAIfmj.jpg" texto="Camisetas del fúbol argentino" %}  
        {% include 'core/tarjeta.html' with titulo="Clubes Internacionales" imagen_url="https://smf.bz/wp-content/uploads/2020/01/elegir-tienda-camisetas-de-futbol.jpg" texto="Camisetas del exterior" %}  
        {% include 'core/tarjeta.html' with titulo="Selecciones" imagen_url="https://cdn.shopify.com/s/files/1/0490/7496/2599/collections/BANNER_2022_CHILE.jpg?v=1666638602" texto="Camisetas de Selecciones del Mundo" %}
        {% include 'core/tarjeta.html' with titulo="Retro" imagen_url="https://media.tycsports.com/files/2023/06/30/587305/nueva-camiseta-retro-de-boca-y-river_862x485.webp" texto="Camisetas históricas" %}
        {% include 'core/tarjeta.html' with titulo="Usadas" imagen_url="https://images.ecestaticos.com/mqllbusfJf_HlmiW_Ks-AMPO8cU=/2x157:2272x1515/1440x810/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F989%2F8a1%2F90f%2F9898a190f63302ff7e085d9010502669.jpg" texto="Camisetas usadas por jugadores profesionales" %}
        {% include 'core/tarjeta.html' with titulo="Vender" imagen_url="https://s1.eestatic.com/2019/02/17/como/redes_sociales-relaciones_publicas-como_hacer_376973019_114958106_1706x960.jpg" texto="Publica y vende esa camiseta que ya no usas!" %}
    </div>
{% endblock content %}

project/apps/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
    | Login
{% endblock title %}

{% block content_title %}
    Ingresar
{% endblock content_title %}

{% block content %}
    
    <form method="post" class="form-control">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{% url 'core:index' %}">
        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
        <a href="{% url 'core:index' %}" class="btn btn-secondary">Cancelar</a>

    </form>

{% endblock content %}

project/apps/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %}
    | Logout
{% endblock title %}

{% block content_title %}
    Has cerrado sesión
{% endblock content_title %}

{% block content %}

    <h3 class="display-4">Gracias por visitar el sitio. Hasta pronto!</h3>

{% endblock content %}

project/apps/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand">Fútbol Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link {% if request.path == '/' %} active {% endif %}" href="{% url 'core:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link {% if '/about/' in request.path %} active {% endif %}" href="{% url 'core:about' %}">Quiénes somos</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link {% if '/producto/' in request.path %} active {% endif %} " href="{% url 'producto:index' %}">Productos</a></li>
                    <li class="nav-item nav-link text-bg-info">{{ user.username }}</li>
                    <li class="nav-item ">
                        <form action="{% url 'core:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark">Salir</button>
                        </form>
                    </li>

                {% else %}
                    <li class="nav-item"><a class="nav-link {% if '/login/' in request.path %} active {% endif %} " href="{% url 'core:login' %}">Ingresar</a></li>
                    <li class="nav-item"><a class="nav-link {% if '/register/' in request.path %} active {% endif %} " href="{% url 'core:register' %}">Crear Cuenta</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

project/apps/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}
    | Crear Cuenta
{% endblock title %}

{% block content_title %}
    Nuevo Usuario
{% endblock content_title %}

{% block content %}
    
    <form method="post" class="form-control">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Crear Cuenta</button>
        <a href="{% url 'core:index' %}" class="btn btn-secondary">Cancelar</a>
    </form>

{% endblock content %}

project/apps/core/templates/core/tarjeta.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
                <img src="{{ imagen_url }}" class="card-img-top">
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer d-flex justify-content-center">
            <a class="btn btn-primary btn-sm" href="{% url 'core:unavailable' %}">Ir</a>
        </div>
    </div>
</div>

project/apps/core/templates/core/unavailable.html
{% extends 'core/base.html' %}

{% block title %}
    | Ver Productos
{% endblock title %}

{% block content_title %}
    Sección no disponible
{% endblock content_title %}

{% block content %}

    <h3 class="display-4">Pronto estaremos actualizando el contenido.</h3>

{% endblock content %}

project/apps/producto/templates/producto/index.html
{% extends 'core/base.html' %}
    
{% block title %}
    | Productos
{% endblock title %}
    
{% block content_title %}
    PRODUCTOS
{% endblock content_title %}

{% block content %}

    <div class="card text-center">
        <div class="card-body">
            <h2 class="card-title">Categorías de Productos</h2>
            <div class="d-flex justify-content-center gap-4">
                <a class="btn btn-primary w-50" href="{% url 'producto:productocategoria_list' %}">Ver Categorías de Productos</a>
                <a class="btn btn-primary w-50" href="{% url 'producto:productocategoria_form' %}">Crear Categorías de Productos</a>
            </div>
        </div>
    </div>

{% endblock content %}

project/apps/producto/templates/producto/productocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    | Productos | Categorías
{% endblock title %}

{% block content_title %}
    Confirmar Eliminación
{% endblock content_title %}


{% block content %}
  <div class="container">
    <h1 class="mt-4"></h1>

    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title">¿Eliminar categoría "{{ object.nombre }}"?</h5>
        <p class="card-text">Una vez confirmado no se puede volver atrás.</p>
      </div>
    </div>

    <div class="mt-4">
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'producto:productocategoria_detail' object.id %}" class="btn btn-secondary">Cancelar</a>
      </form>
    </div>
  </div>
{% endblock content %}

project/apps/producto/templates/producto/productocategoria_detail.html
{% extends 'core/base.html' %}

{% block title %}
    | Producto | Categoría
{% endblock title %}

{% block content_title %}
    Detalle de Categoría de Producto
{% endblock  %}

{% block content %}
  <div class="container">

    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title">{{ object.nombre }}</h5>
        <p class="card-text">{{ object.descripcion }}</p>
      </div>
    </div>

    <div class="mt-4">
      <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-primary">Volver a la Lista</a>
      <a href="{% url 'producto:productocategoria_update' object.id %}" class="btn btn-warning">Editar</a>
      <a href="{% url 'producto:productocategoria_delete' object.id %}" class="btn btn-danger">Eliminar</a>
    </div>
  </div>
{% endblock content %}

project/apps/producto/templates/producto/productocategoria_form.html
{% extends 'core/base.html' %}

{% block title %}
    | Producto | Categoría
{% endblock title %}

{% block content_title %}
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
        Categoría
{% endblock content_title %}

{% block content %}
    
    <form method="post" class="form-control">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-secondary">Cancelar</a>

    </form>


{% endblock content %}

project/apps/producto/templates/producto/productocategoria_list.html
{% extends 'core/base.html' %}

{% block title %}
    | Producto | Categoría
{% endblock title %}

{% block content_title %}
    Categorías de Productos
{% endblock content_title %}

{% block content %}
  <div class="container">
    <div class="mb-4">
      <form method="get">
        <input type="text" class="form-control" name="consulta" placeholder="Buscar Categoría">
      </form>
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th >Nombre</th>
          <th >Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for categoria in object_list %}
          <tr>
            <td>{{ categoria.nombre }}</td>
            <td>
              <a href="{% url 'producto:productocategoria_detail' categoria.id %}" class="btn btn-primary me-2">Detalle</a>
              <a href="{% url 'producto:productocategoria_update' categoria.id %}" class="btn btn-warning me-2">Editar</a>
              <a href="{% url 'producto:productocategoria_delete' categoria.id %}" class="btn btn-danger">Eliminar</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="text-center">No hay categorías disponibles.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}